---
admins:
    - YOUR_Quakenet_ACCOUNT_NAME
duration: 90
configurations_availables: 
    ts:             sharing-ts.cfg
    ctf:            sharing-ctf.cfg
    bomb:           sharing-bomb.cfg
    tdm:            sharing-tdm.cfg
    cah:            sharing-cah.cfg
    ftl:            sharing-ftl.cfg
    uz_ts:          uz_ts.cfg
    uz_ctf:         uz_ctf.cfg
    uz_bomb:        uz_bomb.cfg
maps_availables:
    ut4_turnpike:     ut4_turnpike
    turnpike:         ut4_turnpike
    tp:               ut4_turnpike
    ut4_casa:         ut4_casa
    casa:             ut4_casa
    ut4_orbital_sl:   ut4_orbital_sl
    orbital_sl:       ut4_orbital_sl
    ut4_orbital:      ut4_orbital_sl
    orbital:          ut4_orbital_sl
    ut4_abbey:        ut4_abbey
    abbey:            ut4_abbey
    ut4_abbeyctf:     ut4_abbeyctf
    abbeyctf:         ut4_abbeyctf
    ut4_algiers:      ut4_algiers
    algiers:          ut4_algiers
    ut4_ambush:       ut4_ambush
    ambush:           ut4_ambush
    ut4_austria:      ut4_austria
    austria:          ut4_austria
    ut4_company:      ut4_company
    company:          ut4_company
    ut4_crossing:     ut4_crossing
    crossing:         ut4_crossing
    ut4_docks:        ut4_docks
    docks:            ut4_docks
    ut4_elgin:        ut4_elgin
    elgin:            ut4_elgin
    ut4_harbortown:   ut4_harbortown
    harbortown:       ut4_harbortown
    ut4_kingdom:      ut4_kingdom
    kingdom:          ut4_kingdom
    ut4_kingdom_rc6:  ut4_kingdom_rc6
    kingdom_rc6:      ut4_kingdom_rc6
    ut4_kingpin:      ut4_kingpin
    kingpin:          ut4_kingpin
    ut4_mandolin:     ut4_mandolin
    mandolin:         ut4_mandolin
    ut4_maya:         ut4_maya
    maya:             ut4_maya
    ut4_oildepot:     ut4_oildepot
    oildepot:         ut4_oildepot
    ut4_prague:       ut4_prague
    prague:           ut4_prague
    ut4_prague_v2:    ut4_prague_v2
    prague:           ut4_prague_v2
    ut4_ramelle:      ut4_ramelle
    ramelle:          ut4_ramelle
    ut4_ricochet:     ut4_ricochet
    ricochet:         ut4_ricochet
    ut4_riyadh:       ut4_riyadh
    riyadh:           ut4_riyadh
    ut4_sanctuary:    ut4_sanc
    ut4_sanc:         ut4_sanc
    sanctuary:        ut4_sanc
    sanc:             ut4_sanc
    ut4_suburbs:      ut4_suburbs
    suburbs:          ut4_suburbs
    ut4_subway:       ut4_subway
    subway:           ut4_subway
    ut4_swim:         ut4_swim
    swim:             ut4_swim
    ut4_thingley:     ut4_thingley
    thingley:         ut4_thingley
    ut4_tohunga_b8:   ut4_tohunga_b8
    ut4_tohunga:      ut4_tohunga_b8
    tohunga_b8:       ut4_tohunga_b8
    tohunga:          ut4_tohunga_b8
    ut4_tombs:        ut4_tombs
    tombs:            ut4_tombs
    ut4_toxic:        ut4_toxic
    toxic:            ut4_toxic
    ut4_tunis:        ut4_tunis
    tunis:            ut4_tunis
    ut4_uptown:       ut4_uptown
    uptown:           ut4_uptown
    ut4_paris_v2:     ut4_paris_v2
    ut4_paris:        ut4_paris_v2
    paris:            ut4_paris_v2
    ut4_pandora_b6:   ut4_pandora_b6
    pandora_b6:       ut4_pandora_b6
    ut4_pandora_b7:   ut4_pandora_b7
    pandora:          ut4_pandora_b7
    ut4_desolate_rc1: ut4_desolate_rc1
    ut4_desolate:     ut4_desolate_rc1
    desolate:         ut4_desolate_rc1
    ut4_sliema:       ut4_sliema
    sliema:           ut4_sliema
    ut4_offshore:     ut4_offshore
    offshore:         ut4_offshore
    ut4_beijing_b3:   ut4_beijing_b3
    ut4_beijing:      ut4_beijing_b3
    beijing:          ut4_beijing_b3
    ut4_bohemia:      ut4_bohemia
    bohemia:          ut4_bohemia
    ut4_dust2_v2:     ut4_dust2_v2
    dust2_v2:         ut4_dust2_v2
    dust2:            ut4_dust2_v2
    ut4_subterra:     ut4_subterra
    subterra:         ut4_subterra
    ut4_mykonos_a14:  ut4_mykonos_a14
    ut4_mykonos:      ut4_mykonos_a14
    mykonos:          ut4_mykonos_a14
    ut4_sarlat_alpha4:    ut4_sarlat_alpha4
    ut4_sarlat:           ut4_sarlat_alpha4
    sarlat:               ut4_sarlat_alpha4
    ut4_eyasarcade:       ut4_eyasarcade
    eyasarcade:           ut4_eyasarcade
    ut4_casablanca:       ut4_casablanca
    casablanca:           ut4_casablanca
    ut4_facade_b5:        ut4_facade_b5
    ut4_facade:           ut4_facade_b5
    facade:               ut4_facade_b5
    ut4_cambridge_fixed:  ut4_cambridge_fixed
    ut4_cambridge:        ut4_cambridge_fixed
    cambridge:            ut4_cambridge_fixed
    ut4_crazychristmas:   ut4_crazychristmas
    crazychristmas:       ut4_crazychristmas
    ut4_secretbase:       ut4_secretbase
    secretbase:           ut4_secretbase
    ut4_outback:          ut4_outback
    outback:              ut4_outback
bans:
    - QUAKENET_ACCOUNT_NAME_OF_PPL_YOU_DONT_WANT_TO_SEE
    - dipsy
    - Downuri
bans_messages:
    - "Tu fait trop pitier, tu m soule, vas-y parle à ma main. Si t as pas compris ca veux dire oublie moi hum hum... http://youtu.be/Q4FamibkUH4"
    - "J'écoute pas, t'existes pas, donc vas-y parle à ma main. Si t\'as pas compris ça veux dire non merci hum hum... http://youtu.be/Q4FamibkUH4"
    - "Han, Han, P.I : Pas Intéressée. ... http://youtu.be/Q4FamibkUH4"
    - "Han, han, ÇC : Ça Craint ! ... http://youtu.be/Q4FamibkUH4"
    - "Euh... F.B.I : Fausse bonne idée !... http://youtu.be/Q4FamibkUH4"
    - "Don't talk to me, you're ugly"
    - "Nope."
